### PR TITLE
updates to add sypthon input. makes it OSX only

### PR DESCRIPTION
**Pull request by danzeeeman**
I should probably do #defines for TARGET_OSX so you can pull out sypthon for winders and linux.

@laserpilot and I want to release a binary version of this branch.

### CODE REVIEW

**Comment by smallfly** [comment]
Hi,

Nice! I wanted to do this since a while now.
I think the cleanest way to integrate this would be to create a new example (example-Syphon). This example could include a comment/disclaimer stating that it requires ofxSyphon and it's OS X only.

Would you like to do a new pull request?

Cheers!

**Comment by danzeeeman** [comment]
sure

**Comment by smallfly** [comment]
Great!

**Comment by smallfly** [comment]
Hey,

I'm closing this pull request. I have added an example using Syphon. This is for now in the branch develop.

I'm looking at moving Syphon support to the add-on itself. This would be an option that users could decide to activate or not. I will keep you and @laserpilot posted soon.

Cheers.

**Pull request closed without merging**
